# Deployment config for dashboards
config:
    browser-reports:
        layout: tabs
        config: Dashiki:SimpleRequestBreakdowns
        piwikHost: piwik.wikimedia.org
        piwikId: 8
        hostname: browser-reports.wmflabs.org
        subfolder:

    vital-signs:
        layout: metrics-by-project
        config: Dashiki:VitalSigns
        piwikHost: piwik.wikimedia.org
        piwikId: 8
        hostname: vital-signs.wmflabs.org
        subfolder:

    edit-analysis:
        layout: compare
        config: Dashiki:VisualEditorAndWikitext
        piwikHost: piwik.wikimedia.org
        piwikId: 10
        hostname: edit-analysis.wmflabs.org
        subfolder: compare

    language-reportcard:
        layout: metrics-by-project
        config: Dashiki:LanguageReportcard
        piwikHost:
        piwikId:
        hostname: language-reportcard.wmflabs.org
        subfolder:

    multimedia-health:
        layout: metrics-by-project
        config: Dashiki:MultimediaHealth
        piwikHost: piwik.wikimedia.org
        piwikId: 10
        hostname: edit-analysis.wmflabs.org
        subfolder: multimedia-health

    flow-by-wiki:
        layout: metrics-by-project
        config: Dashiki:FlowByWiki
        piwikHost: piwik.wikimedia.org
        piwikId: 10
        hostname: edit-analysis.wmflabs.org
        subfolder: beta-enables

    flow-reportcard:
        layout: tabs
        config: Dashiki:FlowReportcard
        piwikHost:
        piwikId:
        hostname: flow-reportcard.wmflabs.org
        subfolder:
